[build]
base = "docs/"
command = "true"

[dev]
publish = "docs/"

[[edge_functions]]
  path = "/2015/10/emotional-labor/Emotional_Labor_-_The_MetaFilter_Thread_Condensed.pdf"
  function = "download-tracker"

# vim: sts=2 sw=2 ts=2 et:
