server {
    listen 80;
    server_name localhost;

    # Privacy-friendly analytics by Plausible
    # (The Plausible script automatically disables itself on localhost.)
    location = /418/script.js {
        proxy_pass https://plausible.io/js/pa-_yQiU1Uh0ujA5myugH-gx.js;
        proxy_set_header Host plausible.io;
    }
    location = /418/api/event {
        proxy_pass https://plausible.io/api/event;
        proxy_http_version 1.1;
        proxy_set_header Host plausible.io;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri.html $uri/ =404;
        index index.html;
    }

    error_page 404 /404.html;

    # redirect server error pages to the static page /50x.html
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
# vim: ft=nginx
